#!/bin/bash
ip=`curl "https://check-host.net/ip-info?host=$1" | grep -o "[0-9]\{1,3\}\(\.[0-9]\{1,3\}\)\{3\}</td>" | head -1 | grep -o "[0-9]\{1,3\}\(\.[0-9]\{1,3\}\)\{3\}"`
sudo sed -i "/#Hosts/ a $ip\t\t$1" /etc/hosts	
