#!/bin/bash
if [ $# -eq 0 ]
then
	echo "Usage ./dnsbypass <the domain name> "
	echo "example: ./dnsbypass github.com"
	exit 1;
fi

#sometimes you want to delete
if [ $1  == "-remove" ]
then
	sed -i "/$2/d" /etc/hosts && echo "removed"
	exit 0;
fi

#deletes if the line is already here (i could have made a check instead but who cares?
sed -i "/$1/d" /etc/hosts

ip=`curl "https://check-host.net/ip-info?host=$1" | grep -o "[0-9]\{1,3\}\(\.[0-9]\{1,3\}\)\{3\}</strong>" | head -1 | grep -o "[0-9]\{1,3\}\(\.[0-9]\{1,3\}\)\{3\}"`
if [ $ip != "" ] #sometimes it gives nothing, i have no idea
then
	echo "IP for $1 is $ip"
	sudo sed -i "/#Hosts/ a $ip\t\t$1" /etc/hosts
else
	echo "Error retrieving IP"
fi	
