#!/bin/bash
if [ $# -eq 0 ]
then
	echo "Usage ./dnsbypass <the domain name>"
	echo "example: ./dnsbypass github.com"
	echo "to specify any dns use the second argument <8.8.8.8> (its the default by the way)"
	echo "example : ./dnsbypass 4chan.org 1.1.1.1"
	echo "if you want to delete one route use -remove <the domaine name>"
	exit 1;
fi

#sometimes you want to delete
if [ $1  == "-remove" ]
then
	sed -i "/$2/d" /etc/hosts && echo "removed"
	exit 0;
fi


DNSproxy="8.8.8.8"
if [[ ! -z $2 ]] 
then
	DNSproxy=$2
fi


sed -i "/$1/d" /etc/hosts #supposed to delete the line, to not have two route for a same domain name

ip=($(dig @$DNSproxy +short $1)) #there i use a specific DNS, googles one by default, might change that later
echo $ip

if [ $ip != "" ] #
then
	echo "IP for $1 is $ip"
	echo -e "$ip\t$1" >> /etc/hosts
else
	echo "Error retrieving IP"
fi	
